# Generated by Django 3.1.7 on 2021-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
