# Generated by Django 3.1.7 on 2021-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0003_citylist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
