# Generated by Django 3.1.7 on 2021-04-05 17:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0004_auto_20210404_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylist',
            name='Recommendation',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
