# Generated by Django 3.1.7 on 2021-04-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0018_auto_20210406_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='Recommendation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
