# Generated by Django 3.1.7 on 2021-04-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0020_auto_20210406_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='Recommendation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
