# Generated by Django 3.1.7 on 2021-04-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0023_auto_20210406_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='Recommendation',
            field=models.JSONField(default={'Top 10 Recommendation': ['Elephanta Caves', 'Siddhivinayak Temple', 'Chhatrapati Shivaji Terminus (CST)', 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya', 'ISKCON Temple', 'Girgaon Chowpatty', 'Shri Mahalakshmi Temple', 'Powai Lake']}),
        ),
    ]
