# Generated by Django 3.1.7 on 2021-04-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0025_auto_20210406_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citylist',
            name='Recommendation',
        ),
    ]
