# Generated by Django 3.1.7 on 2021-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indiancity', '0026_remove_citylist_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylist',
            name='recommendation',
            field=models.JSONField(default='list'),
        ),
    ]
